# Site wide configuration (available as site.variable_name)
title: Seunghoon Lee
description: 'a programming blog'
url: https://seunghoonlp.github.io
author: Seunghoon Lee

# Owner configuration
# (leave blank to disable the corresponding sharing button)
owner:
  github: seunghoonlp
  twitter: 
  linkedin: 

attribution:
  theme_name: Lagrange
  theme_url: https://lenpaul.github.io/Lagrange/

# Disqus comments configuration (leave blank to disable comments)
disqus_shortname: 

# Jekyll configuration
permalink: /:year/:month/:day/:title/
paginate: 3

# Markdown
markdown: kramdown
highlighter: rouge

# Gems
plugins: ['jekyll-paginate']

# Exclude
exclude: ['README.md']

# Additional collections
# https://jekyllrb.com/docs/collections/
collections:
  bites:
    output: true
    permalink: /:collection/:year/:month/:day/:title
